### ISSUE TITLE
Android BUILD FAILED

### ISSUE THREAD

**Issue by King143** [doo/scanbot-sdk-example-ionic2#11]
BUILD FAILED in 21s
cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find support-vector-drawable.aar (com.android.support:support-vector-drawable:27.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-vector-drawable/27.1.1/support-vector-drawable-27.1.1.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
[ERROR] An error occurred while running cordova run android (exit code 1).

**Comment by eddyfrank** [comment]
It's not an issue of the Scanbot SDK.
Looks like the Android Support Libs were removed from jcenter maven repos.
E.g. see https://github.com/facebook/react-native/issues/21916 and try to apply the workaround by changing the order of repositories.

We will publish an update of the Scanbot Cordova Plugin with a fix soon.

**Comment by eddyfrank** [comment]
Hey @King143,

Android Support Libs (support-compat, support-vector-drawable, etc) are not available on https://jcenter.bintray.com  anymore. And it looks like they are still referenced in your local Gradle caches.
(Not sure why they were removed from jcenter repos. Welcome in the world of Android development  ;-) ).
However, these libs are available in Googles maven repo (defined as `google()` in gradle files), which is also included in our plugin gradle file.

So you just need to delete Gradle caches and then re-init and re-build the whole project again.

Gradle caches folder can be found here:
- On Windows: %USER_HOME%\.gradle/caches/
- On Mac/Unix: $HOME/.gradle/caches/
Also see https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache

```
# delete Gradle caches folder:
rm -rf $HOME/.gradle/caches/

# re-init and re-build the project:
cd scanbot-sdk-example-ionic2/
rm -rf node_modules/
rm -rf platforms/
rm -rf plugins/
npm install
ionic cordova prepare
ionic cordova build android
```

Best,
Eddy
