### ISSUE TITLE
npm i error

### ISSUE THREAD

**Issue by Sampath-Lokuge** [doo/scanbot-sdk-example-ionic2#12]
Hi,

I have cloned the app and run `npm i`. But it shows below error. Any clue?

_Note:_ I don't have any issue with my other ionic projects.

> $ npm i
> 
> > node-sass@4.5.3 install D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-64_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-64_binding.node":
> 
> HTTP error 404 Not Found
> 
> Hint: If github.com is not accessible in your location
>       try setting a proxy via HTTP_PROXY, e.g.
> 
>       export HTTP_PROXY=http://example.com:1234
> 
> or configure npm proxy via
> 
>       npm config set proxy http://example.com:8080
> 
> > uglifyjs-webpack-plugin@0.4.6 postinstall D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\uglifyjs-webpack-plugin
> > node lib/post_install.js
> 
> 
> > node-sass@4.5.3 postinstall D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\node-sass
> > node scripts/build.js
> 
> Building: C:\Program Files\nodejs\node.exe D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=gyp info it worked if it ends with ok
> gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> gyp verb cli   'D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\node-gyp\\bin\\node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library=' ]
> gyp info using node-gyp@3.7.0
> gyp info using node@10.13.0 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` failed Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:89:16
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
> gyp verb `which` failed  python2 { Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:89:16
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
> gyp verb `which` failed   stack:
> gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\which\\which.js:13:12)\n    at F (D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\which\\which.js:68:19)\n    at E (D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\which\\which.js:80:29)\n    at D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\which\\which.js:89:16\n    at D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\isexe\\index.js:42:5\n    at D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
> gyp verb `which` failed   code: 'ENOENT' }
> gyp verb check python checking for Python executable "python" in the PATH
> gyp verb `which` failed Error: not found: python
> gyp verb `which` failed     at getNotFoundError (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:89:16
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
> gyp verb `which` failed  python { Error: not found: python
> gyp verb `which` failed     at getNotFoundError (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\which\which.js:89:16
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:154:21)
> gyp verb `which` failed   stack:
> gyp verb `which` failed    'Error: not found: python\n    at getNotFoundError (D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\which\\which.js:13:12)\n    at F (D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\which\\which.js:68:19)\n    at E (D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\which\\which.js:80:29)\n    at D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\which\\which.js:89:16\n    at D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\isexe\\index.js:42:5\n    at D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:154:21)',
> gyp verb `which` failed   code: 'ENOENT' }
> gyp verb could not find "python". checking python launcher
> gyp verb could not find "python". guessing location
> gyp verb ensuring that file exists: C:\Python27\python.exe
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at PythonFinder.failNoPython (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\node-gyp\lib\configure.js:492:19)
> gyp ERR! stack     at PythonFinder.<anonymous> (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\node-gyp\lib\configure.js:517:16)
> gyp ERR! stack     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Clients\\Simplessus\\scanbot-sdk-example-ionic2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\node-sass
> gyp ERR! node -v v10.13.0
> gyp ERR! node-gyp -v v3.7.0
> gyp ERR! not ok
> Build failed with error code: 1
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@4.5.3 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Sampath\AppData\Roaming\npm-cache\_logs\2018-11-30T14_28_50_822Z-debug.log

Ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.5.0 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.2
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 8 other plugins)

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by tailsu** [comment]
Hi,

This appears to be a problem with your development environment, not with scanbot itself. Ionic requires node-sass to function and a prebuilt node-sass binary is not available for Windows for your node.js version. Since it's not available you'll need python and the Visual C++ compiler installed on your machine before node-sass can be installed successfully.

My recommendation would be to get a basic ionic project up and running on your machine first. Only then try to run this project.

**Comment by Sampath-Lokuge** [comment]
Hi,

Hope you didn't read this `Note: I don't have any issue with my other ionic projects.`. I'm developing Ionic apps for 2 years and your SDK is also for a German client. I don't have any issue with my environment. Your thoughts then?

**Comment by Sampath-Lokuge** [comment]
Ok sure. Thanks for the tip. I'll let you know if I'll have any further issues after upgrading.

**Comment by Sampath-Lokuge** [comment]
I have updated the `package.json` file like so and no issues now.

> {
  "name": "scanbot-sdk-example-ionic2",
  "version": "1.0.2",
  "author": "doo GmbH",
  "homepage": "https://scanbot.io/sdk.html",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/camera": "^4.7.0",
    "@ionic-native/core": "4.3.2",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "4.3.2",
    "@ionic/storage": "2.1.3",
    "cordova-android": "^7.1.4",
    "cordova-ios": "^4.5.5",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-scanbot-sdk": "^2.1.1",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-whitelist": "^1.3.1",
    "ionic-angular": "3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.2.1",
    "typescript": "2.6.2"
  },
  "description": "Example App for Scanbot SDK Cordova Plugin with Ionic 2+ Framework",
  "cordova": {
    "platforms": [
      "ios",
      "android"
    ],
    "plugins": {
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-camera": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "Allow gallery access",
        "CAMERA_USAGE_DESCRIPTION": " ",
        "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
      },
      "cordova-plugin-scanbot-sdk": {}
    }
  }
}
