### ISSUE TITLE
Angular Can't resolve all parameters for SdkUiPage

### ISSUE THREAD

**Issue by Sampath-Lokuge** [doo/scanbot-sdk-example-ionic2#13]
Hi,

I have cloned the code and run `npm i` and I can run the app. But it shows below error on `sdk-ui.ts` page. Can you tell me how to solve this?

> [Angular] Can't resolve all parameters for SdkUiPage in d:/Clients/Simplessus/scanbot-sdk-example-ionic2/src/pages/sdk-ui/sdk-ui.ts: ([object Object], [object Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object]).
> (alias) Component(obj: Component): TypeDecorator
> import Component

**Comment by eddyfrank** [comment]
Is this issue still relevant?
Based on your last issue https://github.com/doo/scanbot-sdk-example-ionic2/issues/14  you got this app running.

**Comment by Sampath-Lokuge** [comment]
No. This is a different issue on your sample app. It seems TS issue.

![er](https://user-images.githubusercontent.com/5206526/49369418-63794300-f717-11e8-958f-14f2df11e4e6.png)

**Comment by eddyfrank** [comment]
As already pointed out in https://github.com/doo/scanbot-sdk-example-ionic2/issues/18#issuecomment-444095914 - this issue is not related to Scanbot SDK.
