### ISSUE TITLE
How to test this app with my licence key

### ISSUE THREAD

**Issue by Sampath-Lokuge** [doo/scanbot-sdk-example-ionic2#14]
Hi,

I have cloned this app and running fine on the device. So can you tell me how can I test its functionality using my licence key? If I'll change its bundle id as my app's id then will it work or what should I do?

**Comment by eddyfrank** [comment]
Just pass your license key on initialization of the SDK:
https://github.com/doo/scanbot-sdk-example-ionic2/blob/master/src/services/sdk-initializer.ts#L7

Please note that a license key is bound to the App ID (bundle ID).
You can change the App ID of a Cordova/Ionic project in `config.xml`:
https://github.com/doo/scanbot-sdk-example-ionic2/blob/master/config.xml#L2
```
<widget id="io.scanbot.example.sdk.ionic2" ...
```

After making the changes in `config.xml`, make sure to re-create the platforms (`ios` and `android`).
```
rm -rf platforms/
rm -rf plugins/
ionic cordova prepare
```

**Comment by Sampath-Lokuge** [comment]
`Q:` How long will you take to release a `production key`? We have already applied it.

**Comment by eddyfrank** [comment]
@Sampath-Lokuge 
Would you mind reaching out to our sales experts via sdk@scanbot.io to discuss these in further detail? Herewith you could also find out more about our licensing model.
