### ISSUE TITLE
No entry on config.xml file

### ISSUE THREAD

**Issue by Sampath-Lokuge** [doo/scanbot-sdk-example-ionic2#15]
Hi,

I have used this `npm i cordova-plugin-scanbot-sdk`. But it doesn't put any entry on `config.xml` file. Can you tell me why? Your sample project where it has 3 entries. i.e. 1 on `.xml` file and 2 on `.json` file.

This is the only entry on my Ionic 3 project.

_package.json_

`"cordova-plugin-scanbot-sdk": "^2.1.1",`

> Ionic:
> 
>    ionic (Ionic CLI)  : 4.5.0 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\ionic)
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.1
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
>    Cordova Platforms     : android 7.1.2
>    Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.3, (and 8 other plugins)
> 
> System:
> 
>    NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
>    npm    : 6.4.1
>    OS     : Windows 10

**Comment by tailsu** [comment]
That's not how it works. The correct command is `ionic cordova plugin add cordova-plugin-scanbot-sdk`

https://ionicframework.com/docs/cli/cordova/plugin/

**Comment by Sampath-Lokuge** [comment]
I have done this `ionic cordova plugin add cordova-plugin-scanbot-sdk`. But still I cannot see the `CAMERA_USAGE_DESCRIPTION` text. Any thoughts? @tailsu 

_.json_

> "cordova-plugin-scanbot-sdk": "2.1.1",
> "cordova-plugin-scanbot-sdk": {}

_.xml_

> <plugin name="cordova-plugin-scanbot-sdk" spec="2.1.1" />
