### ISSUE TITLE
Move the top menu bar to the bottom

### ISSUE THREAD

**Issue by Sampath-Lokuge** [doo/scanbot-sdk-example-ionic2#16]
Hi,

Can we move the top menu bar to the bottom?

![sc](https://user-images.githubusercontent.com/5206526/49395889-baa20680-f75d-11e8-853d-28a80d2703d4.png)

**Comment by tailsu** [comment]
No, there's no configuration option for that. What you can do is use the scanner components from the Android Scanbot SDK and build the activity yourself as a custom Cordova plugin.
