### ISSUE TITLE
 Put the Import text with click event to open the phone gallery

### ISSUE THREAD

**Issue by Sampath-Lokuge** [doo/scanbot-sdk-example-ionic2#17]
Hi,

Can I put the `Import` text with `click` event to open the phone gallery with this SDK?

![sc2](https://user-images.githubusercontent.com/5206526/49396434-17ea8780-f75f-11e8-8b85-df7b844c749d.png)

**Comment by tailsu** [comment]
No, there's no configuration option for that. What you can do is use the scanner components from the Android Scanbot SDK and build the activity yourself as a custom Cordova plugin.
