### ISSUE TITLE
 Error: The Angular AoT build failed.

### ISSUE THREAD

**Issue by Sampath-Lokuge** [doo/scanbot-sdk-example-ionic2#18]
Hi,

I have run this on your sample project: ` ionic cordova run android --prod --device`.

Then it shows this error:

> $ ionic cordova run android --prod --device
> > ionic-app-scripts build --prod --target cordova --platform android
> [15:44:01]  ionic-app-scripts 3.2.1
> [15:44:01]  build prod started ...
> [15:44:01]  clean started ...
> [15:44:01]  clean finished in 3 ms
> [15:44:01]  copy started ...
> [15:44:01]  deeplinks started ...
> [15:44:01]  deeplinks finished in 62 ms
> [15:44:01]  ngc started ...
> [15:44:04]  typescript error
>             Can't resolve all parameters for SdkUiPage in
>             D:/Clients/Simplessus/scanbot-sdk-example-ionic2/src/pages/sdk-ui/sdk-ui.ts: ([object Object], [object
>             Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object]).
> 
> [15:44:04]  ionic-app-script task: "build"
> [15:44:04]  Error: The Angular AoT build failed. See the issues above
> Error: The Angular AoT build failed. See the issues above
>     at D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:237:55
>     at step (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
>     at Object.next (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
>     at fulfilled (D:\Clients\Simplessus\scanbot-sdk-example-ionic2\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
> [ERROR] An error occurred while running subprocess ionic-app-scripts.
> 
>         ionic-app-scripts build --prod --target cordova --platform android exited with exit code 1.
> 
>         Re-running this command with the --verbose flag may provide more information.

**Related issues:** 

https://github.com/doo/scanbot-sdk-example-ionic2/issues/13
https://github.com/doo/scanbot-sdk-example-ionic2/issues/12

`Note:` We are using `AOT` and `lazy loading` on our project.

**Comment by eddyfrank** [comment]
Please kindly note:

- This is just an **example app**, based on current module configurations provided in package.json and config.xml. It does not reflect all available versions or combinations of Ionic/Angular/Cordova/etc out there. Also, it is not optimized for release/production builds. The main point of this example app is to keep it simple and to demonstrate the SDK API. Depending on your environment (Node, Ionic, Angular, Cordova, etc), you might have to adjust some parts of this app or of your project. That's no reason for opening a GitHub issue. (by the way: it works fine here with node 8.x and ionic CLI 4.5.0)

- All issues you reported are **not** related to Scanbot SDK. We hope for your kind understanding that we can not provide technical support for general development questions not related to the purchased product.

Again, please reach out to our sales experts via sdk@scanbot.io to discuss further support details.
Thanks for your understanding.
