### ISSUE TITLE
Getting error 403

### ISSUE THREAD

**Issue by bhandaribhumin** [doo/scanbot-sdk-example-ionic2#2]
getting error while 
> npm install

------------------------------->

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5
.0/win32-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win3
2-x64-48_binding.node":

HTTP error 403 Forbidden

**Comment by eddyfrank** [comment]
Hi @bhandaribhumin,

this is not an issue of the Scanbot SDK.

Looks like a temporary server issue when fetching some npm modules required by Ionic.
Please check our npm installation, clear npm caches and try again.

Regards,
Eddy

**Comment by eddyfrank** [comment]
I close this issue since it's not related to Scanbot SDK Plugin.
