### ISSUE TITLE
Unable to install with node 8

### ISSUE THREAD

**Issue by WalMast** [doo/scanbot-sdk-example-ionic2#3]
An FYI:
I got the project, did an `npm install`, and got error: 

```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

HTTP error 404 Not Found
```

I believe this is because node-sass has to be at least version 4.5.3 for compatibility with node 8.

Instead of `npm install`, I did `npm update`, and the node modules installed OK (now with node-sass 4.7.2).

**Comment by eddyfrank** [comment]
Hi @WalMast ,
thanks for your input.

Looks like a typical npm dependencies issue. 

I close this issue since it's not related to Scanbot SDK Plugin.
