### ISSUE TITLE
Auto-Snap Questions

### ISSUE THREAD

**Issue by brassier** [doo/scanbot-sdk-example-ionic2#9]
I'm testing out the Scanbot SDK a bit.  I have things set up on Android and iOS.  It works pretty well and was easy to set up - great work!  

I'm curious about auto-snapping consistency.  I've noticed:

1. In iOS it occasionally will not give guidance messages and requires me to press the snap button before it will take a picture.  It acts almost like manual snap mode.  It does give guidance at times though.  
1. In Android the guidance can lock up, where it has the same guidance no matter how you move the camera viewer.  Cancelling and re-opening seems to clear that.

Are these known inconsistency issues with auto-snap?  I assume my 1 minute trial wouldn't be the cause of something like this?

**Comment by eddyfrank** [comment]
We haven't received a response to this issue and are assuming that this is solved.

**Comment by brassier** [comment]
I just recently got a full license and will be doing more testing in the coming couple weeks.  If I see this happening with the full license I'll open a new issue.  Thanks!
